### ISSUE TITLE
FIX index not defined

### ISSUE THREAD

**Issue by wabscale** [AnubisLMS/Mayat#3]
index is not defined here: 

https://github.com/AnubisLMS/AntiCheat/blob/main/anubis_pd/C_AST.py#L26

im pretty sure it is referencing index from main? 

https://github.com/AnubisLMS/AntiCheat/blob/main/anubis_pd/main.py#L15

**Comment by AlpacaMax** [comment]
Correct. Relying on global variables is a bad practice though. I'll change it.

BTW you kinda messed up the file structure I want to achieve. What I did for my previous PR was to separate the C-specific thing out of the matching algorithm so that in the future we can create other frontends for other programming languages. So what I want is to separate these different frontends into different directories. I'll fix that as well.

**Comment by AlpacaMax** [comment]
Fixed!
